### ISSUE TITLE
Ansible best practices

### ISSUE THREAD

**Issue by luiscachog** [doxmx/meetups-topics#1]
I want to know some of the best practices for Ansible. playbooks, some workflows and tools.

**Comment by tonyskapunk** [comment]
I could talk about this one, but not this coming session, would have to be for the following one

**Comment by luiscachog** [comment]
@tonyskapunk are you down for Sept 20?

**Comment by tonyskapunk** [comment]
That should be enough time, so yes ;)

**Comment by luiscachog** [comment]
Scheduled for Sept/20/2019

**Comment by tonyskapunk** [comment]
Contenido de la presentación: https://gist.github.com/tonyskapunk/99bf0c9ce054b7b9392e

**Comment by luiscachog** [comment]
Kudos for the presentation! Good material and examples!
