### ISSUE TITLE
All-in-one K8 cluster with kubeadm

### ISSUE THREAD

**Issue by tonyskapunk** [doxmx/meetups-topics#10]
Would be nice to have a demo to get started with k8 using all-in-one cluster to start playing with it.
Example
- Minimal Requirements
- Gotchas/Common problems
- Tear down/Clean up
- Upgrading cluster
- Adding nodes
- Advantages/Disadvantages with other tools/ways to build k8 clusters

**Comment by luiscachog** [comment]
@josueneo after you were nominated, next step is to assign a date for the talk, starting Oct 4th and considering 2 weeks apart, what date do you want to present?

**Comment by tonyskapunk** [comment]
@josueneo per our chat I'm adding you for Oct 4th.

Thanks!

**Comment by tonyskapunk** [comment]
@josueneo asked to move this one to Oct 11th, moved in the project.

Thanks @josueneo!

**Comment by josueneo** [comment]
Install runtimes: kubelet, kubectl, kubeadm and other dependencies:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime

Bootstrap the kubernetes cluster:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

Upgrade guide:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/

**Comment by tonyskapunk** [comment]
Thanks for the presentation @josueneo!! :smile:
