### ISSUE TITLE
Cómo crear un homelab para los primeros pasos en Linux

### ISSUE THREAD

**Issue by gsoteloe** [doxmx/meetups-topics#12]
Lo mejor para aprender una tecnología nueva es practicar, practicar y practicar. En esta charla, orientada a principiantes, se puede abordar un par de estrategias para crear un homelab para prácticas.

**Comment by gsoteloe** [comment]
I volunteer for this one o/

**Comment by tonyskapunk** [comment]
@0x2141 Oct ~14th~ 18th is available are you OK with that date?

**Comment by gsoteloe** [comment]
Sounds great, thanks, Sir.

**Comment by tonyskapunk** [comment]
I completely drop the ball scheduling this one :disappointed: , @0x2141 would you be available to do Nov 8th or Nov 15th? both are available

**Comment by tonyskapunk** [comment]
Thanks for the presentation @0x2141 :tada: 

Do you mind sharing your presentation here: https://github.com/doxmx/talks ? I'll close this one once that's done! Thanks!
