### ISSUE TITLE
Informal/unprepared talk about k3s, from the edge to beyond

### ISSUE THREAD

**Issue by fmoctezuma** [doxmx/meetups-topics#18]
I can share some notes and experience running k3s on one edge device
Tags: k3s containerd, GPU, Monitoring, Edge, cloud

**Comment by fmoctezuma** [comment]
**Sharing some info here since I didn't create actual slides for the presentation sorry about this.**

* k3s - https://k3s.io
* Jetson Nano - https://developer.nvidia.com/embedded/jetson-nano-developer-kit
* And - https://devblogs.nvidia.com/jetson-nano-ai-computing/
* Traefik as LB for K3s - https://containo.us/traefik/
* Sqlite replacing etcd - https://www.sqlite.org/index.html
* Prometheus Exporters list - https://prometheus.io/docs/instrumenting/exporters
* containerd on k3s - https://rancher.com/docs/k3s/latest/en/advanced/

**How to create a prometheus exporter**
* Writting exporters - https://prometheus.io/docs/instrumenting/writing_exporters/
* Noobs guide to create a prometheus exporter - https://rsmitty.github.io/Prometheus-Exporters
* PromQL for humans - https://timber.io/blog/promql-for-humans/

**NVML not supported on Tegra devices**
* NVML is not supported on tegra devices - https://devtalk.nvidia.com/default/topic/1064580/jetson-nano/libnvidia-ml-so-and-nvml-h-support/post/5391686/#5391686
* and - https://docs.nvidia.com/deploy/nvml-api/nvml-api-reference.html#nvml-api-reference

**About Tegra**
* Tegra wiki - https://en.wikipedia.org/wiki/Tegra
* Nintendo Switch - https://www.eurogamer.net/articles/digitalfoundry-2019-new-nintendo-switch-hac-001-01-review
* https://www.theverge.com/circuitbreaker/2019/7/10/20689379/nintendo-switch-update-fcc-change-cpu-nvidia-tegra-soc-nand

**Example outputs from tegrastats**

Example Output for Jetson TX1
```
RAM 1179/3983MB (lfb 120x4MB) IRAM 0/252kB(lfb 252kB) CPU [1%@102,4%@102,0%@102,0%@102] EMC_FREQ 7%@408 GR3D_FREQ 0%@76 APE 25 AO@42.5C CPU@37.5C GPU@39C PLL@37C Tdiode@42.75C PMIC@100C Tboard@42C thermal@38.5C VDD_IN 2532/2698 VDD_CPU 76/178 VDD_GPU 19/19
```

Example Output for Jetson TX2 series
```
RAM 1345/7829MB (lfb 1290x4MB) SWAP 0/512MB (cached 0MB) CPU [2%@345,off,off,off,off,off] EMC_FREQ 13%@40 GR3D_FREQ 0%@114 APE 150 BCPU@35C MCPU@35C GPU@41C PLL@35C AO@35.5C Tboard@35C Tdiode@36C PMIC@100C thermal@35.5C VDD_IN 2003/2658 VDD_CPU 320/518 VDD_GPU 400/735 VDD_SOC 400/415 VDD_WIFI 0/0 VDD_DDR 240/348
```

Example Output for Jetson AGX Xavier
```
RAM 1903/15692MB (lfb 3251x4MB) CPU [1%@1190,1%@1190,2%@1190,0%@1190,0%@1190,0%@1190,0%@1190,0%@1190] EMC_FREQ 0% GR3D_FREQ 0% AO@32.5C GPU@32C Tboard@32C Tdiode@34.75C AUX@31.5C CPU@33.5C thermal@32.9C PMIC@100C GPU 0/0 CPU 216/216 SOC 864/864 CV 0/0 VDDRQ 144/144 SYS5V 1889/1889
```

I haven't committed my code just yet, need to work on a couple of pending metrics

**Comment by tonyskapunk** [comment]
Thanks for sharing @fmoctezuma !!
