### ISSUE TITLE
Elastic - primer

### ISSUE THREAD

**Issue by tonyskapunk** [doxmx/meetups-topics#9]
- What is Elastic?
- Why Elastic?
- Common use cases
- When to use Elastic
- When *not* to use Elastic
- Alternatives

---
cc: @Imoq  @kwame @betordz @arturoera

**Comment by betordz** [comment]
I volunteer for this one

**Comment by luiscachog** [comment]
Two in a row!!
@betordz, confirm, what day do you want? Starting Oct 4th ( Considering 2 weeks apart).

**Comment by tonyskapunk** [comment]
@betordz what dates do you prefer? See the availability here: https://github.com/doxmx/meetups-topics/projects/1

**Comment by betordz** [comment]
@tonyskapunk - I scheduled it

**Comment by tonyskapunk** [comment]
Thanks @betordz for the presentation, it was great and super clear, you should be a teacher :man_teacher:  oh wait!! :stuck_out_tongue_closed_eyes: 

The content is available here:  https://github.com/doxmx/talks/tree/master/intro-elasticsearch
